name: mustache
version: 1.1.1
author: Greg Lowe <greg@vis.net.nz>
description: Mustache template library
homepage: https://github.com/xxgreg/mustache
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
analyzer:
  strong-mode: true
